//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prisonsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependent
    {
        public int did { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> prisonid { get; set; }
        public string dfname { get; set; }
        public string dlname { get; set; }
        public string realationship { get; set; }
        public Nullable<int> phone { get; set; }
    
        public virtual prison prison { get; set; }
        public virtual prisoner prisoner { get; set; }
    }
}
