//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prisonsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class jailor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jailor()
        {
            this.prisoncells = new HashSet<prisoncell>();
            this.prisoners = new HashSet<prisoner>();
        }
    
        public int jeid { get; set; }
        public Nullable<int> jprisonid { get; set; }
    
        public virtual emploee emploee { get; set; }
        public virtual prison prison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisoncell> prisoncells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisoner> prisoners { get; set; }
    }
}
