//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prisonsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class manager
    {
        public int meid { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<int> pmeid { get; set; }
    
        public virtual emploee emploee { get; set; }
        public virtual prison prison { get; set; }
    }
}
