//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prisonsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc
    {
        public int eid { get; set; }
        public Nullable<int> prisonid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string job { get; set; }
        public int pcid { get; set; }
        public string name { get; set; }
    }
}
