//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prisonsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisoncell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prisoncell()
        {
            this.prisoners = new HashSet<prisoner>();
        }
    
        public int pcid { get; set; }
        public Nullable<int> prisonid { get; set; }
        public Nullable<int> jeid { get; set; }
        public string name { get; set; }
    
        public virtual jailor jailor { get; set; }
        public virtual prison prison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisoner> prisoners { get; set; }
    }
}
