//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prisonsystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisoner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prisoner()
        {
            this.dependents = new HashSet<dependent>();
        }
    
        public int pid { get; set; }
        public Nullable<int> pjeid { get; set; }
        public Nullable<int> pcid { get; set; }
        public Nullable<int> prisonid { get; set; }
        public string pfname { get; set; }
        public string plname { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string offence { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> freedate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dependent> dependents { get; set; }
        public virtual jailor jailor { get; set; }
        public virtual prison prison { get; set; }
        public virtual prisoncell prisoncell { get; set; }
    }
}
